sudo: required
language: python

services:
  - docker

install:
  - pip install ome-ansible-molecule-dependencies

script:
  - cd $PLAYBOOKDIR && molecule test

env:
  - PLAYBOOKDIR=public-user
  - PLAYBOOKDIR=three-nodes
