# Install OMERO.server and OMERO.web with a public user on localhost

- hosts: all
  roles:

    - role: openmicroscopy.postgresql
      postgresql_users_databases:
      - user: omero
        password: omero
        databases: [omero]

    - role: openmicroscopy.omero-server

    - role: openmicroscopy.omero-web
      omero_web_config_set:
        omero.web.public.enabled: True
        omero.web.public.server_id: 1
        omero.web.public.user: public
        omero.web.public.password: "{{ omero_web_public_password }}"
        omero.web.public.url_filter: "^/(webadmin/myphoto/|webclient/(?!(action|annotate_(file|tags|comment|rating|map)|script_ui|ome_tiff|figure_script))|webgateway/(?!(archived_files|download_as)))"

    # This role only works on OMERO 5.3+
    - role: omero-user
      omero_user_bin_omero: /opt/omero/server/OMERO.server/bin/omero
      omero_user_system: omero-server
      omero_user_admin_user: root
      omero_user_admin_pass: omero
      omero_group_create:
      - name: demo
        type: read-only
      omero_user_create:
      - login: public
        firstname: public
        lastname: user
        password: "{{ omero_web_public_password }}"
        groups: "--group-name demo"

  vars:
    omero_web_public_password: public
    postgresql_version: "9.6"
